use_frameworks!
inhibit_all_warnings!
platform:ios,'8.0'

target 'ZhiMaBaoBao' do
pod 'FMDB', '~> 2.6.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'MJExtension', '~> 3.0.13' 
pod 'MJRefresh', '~> 3.1.12'
pod 'CocoaAsyncSocket', '~> 7.5.0'
pod 'Masonry', '~> 1.0.1'
pod 'RegexKitLite', '~> 4.0'
pod 'SDWebImage', '~> 3.8.1'

end
